name: CI - Worker
on:
  push:
    branches: [ "main", "develop", "test" ]
  pull_request:
    branches: [ "main", "develop", "test" ]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validar docker-compose
        run: docker-compose config 
  
  build-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Construir imagen WORKER
        run: docker build -t worker-app ./worker

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set image name
        run: echo "IMAGE_NAME=worker-app" >> $GITHUB_ENV

      - name: Tag image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
